# Generated by Django 4.0.2 on 2022-07-28 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DA_generator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='number',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='buyer',
            name='buyer_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='buyer_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='contact_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='contact_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='contact_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
