# Generated by Django 4.0.2 on 2022-07-28 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DA_generator', '0002_remove_buyer_contact_remove_buyer_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DAInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=100)),
                ('fins_required_1', models.CharField(max_length=100)),
                ('fins_required_2', models.CharField(max_length=100)),
                ('previous_contact', models.CharField(max_length=100)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DA_generator.buyer')),
            ],
        ),
    ]
