# Generated by Django 4.0.2 on 2022-07-28 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DA_generator', '0003_dainfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dainfo',
            name='buyer',
        ),
    ]
