# Generated by Django 4.0.2 on 2022-07-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DA_generator', '0004_remove_dainfo_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='buyer_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='contact_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='contact_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dainfo',
            name='fins_required_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dainfo',
            name='fins_required_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dainfo',
            name='previous_contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dainfo',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
