# Generated by Django 3.1.6 on 2023-10-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DA_generator', '0006_auto_20220816_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dainfo',
            old_name='supplier_name',
            new_name='sender',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='contact_number',
        ),
        migrations.AddField(
            model_name='buyer',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
