# Generated by Django 4.2.6 on 2023-10-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DA_generator', '0009_remove_buyerform_customer_name_dainfo_contact_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerform',
            name='buyer_number',
            field=models.IntegerField(null=True),
        ),
    ]
