# Generated by Django 4.2.6 on 2023-10-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DA_generator', '0010_alter_buyerform_buyer_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyerdb',
            name='id',
        ),
        migrations.AlterField(
            model_name='buyerdb',
            name='buyer_number',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
    ]
