# Generated by Django 4.2.6 on 2023-10-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DA_generator', '0012_alter_buyerdb_buyer_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerdb',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buyerdb',
            name='buyer_number',
            field=models.IntegerField(null=True),
        ),
    ]
