# Generated by Django 4.2.6 on 2023-10-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DA_generator', '0013_buyerdb_id_alter_buyerdb_buyer_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerdb',
            name='buyer_number',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
